const SUPPORTED_LANGUAGES = [
  { id: "af-ZA", name: "Afrikaans (South Africa)" },
  { id: "am-ET", name: "Amharic (Ethiopia)" },
  { id: "ar-AE", name: "Arabic (U.A.E.)" },
  { id: "ar-BH", name: "Arabic (Bahrain)" },
  { id: "ar-DZ", name: "Arabic (Algeria)" },
  { id: "ar-EG", name: "Arabic (Egypt)" },
  { id: "ar-IQ", name: "Arabic (Iraq)" },
  { id: "ar-JO", name: "Arabic (Jordan)" },
  { id: "ar-KW", name: "Arabic (Kuwait)" },
  { id: "ar-LB", name: "Arabic (Lebanon)" },
  { id: "ar-LY", name: "Arabic (Libya)" },
  { id: "ar-MA", name: "Arabic (Morocco)" },
  { id: "ar-OM", name: "Arabic (Oman)" },
  { id: "ar-QA", name: "Arabic (Qatar)" },
  { id: "ar-SA", name: "Arabic (Saudi Arabia)" },
  { id: "ar-PS", name: "Arabic (Palestine)" },
  { id: "ar-SD", name: "Arabic (Sudan)" },
  { id: "ar-SY", name: "Arabic (Syria)" },
  { id: "ar-TN", name: "Arabic (Tunisia)" },
  { id: "ar-YE", name: "Arabic (Yemen)" },
  { id: "bn-BD", name: "Bengali (Bangladesh) / বাংলা (বাংলাদেশ)" },
  { id: "bn-IN", name: "Bengali (India) / বাংলা (ভারত)" },
  { id: "eu-ES", name: "Basque (Spain)" },
  { id: "bg-BG", name: "Bulgarian (Bulgaria)" },
  { id: "ca-ES", name: "Catalan (Spain)" },
  { id: "chr-US", name: "Cherokee (United States)" },
  { id: "cmn-Hans-CN", name: "Chinese Mandarin (Mainland)" },
  { id: "cmn-Hans-HK", name: "Chinese Mandarin (Hong Kong)" },
  { id: "cmn-Hant-TW", name: "Chinese Mandarin (Taiwan)" },
  { id: "yue-Hant-HK", name: "Chinese Cantonese (Hong Kong)" },
  { id: "hr-HR", name: "Croatian (Croatia)" },
  { id: "cs-CZ", name: "Czech (Czech Republic)" },
  { id: "da-DK", name: "Danish (Denmark)" },
  { id: "nl-NL", name: "Dutch (Netherlands)" },
  { id: "en-AU", name: "English (Australia)" },
  { id: "en-CA", name: "English (Canada)" },
  { id: "en-IN", name: "English (India)" },
  { id: "en-KE", name: "English (Kenya)" },
  { id: "en-TZ", name: "English (Tanzania)" },
  { id: "en-GH", name: "English (Ghana)" },
  { id: "en-NZ", name: "English (New Zealand)" },
  { id: "en-NG", name: "English (Nigeria)" },
  { id: "en-ZA", name: "English (South Africa)" },
  { id: "en-PH", name: "English (Philippines)" },
  { id: "en-GB", name: "English (United Kingdom)" },
  { id: "en-US", name: "English (United States)" },
  { id: "et-EE", name: "Estonian (Estonia)" },
  { id: "fil-PH", name: "Filipino (Philippines)" },
  { id: "fi-FI", name: "Finnish (Finland)" },
  { id: "fr-FR", name: "French (France)" },
  { id: "gl-ES", name: "Galician (Spain)" },
  { id: "ka-GE", name: "Georgian (Georgia)" },
  { id: "de-DE", name: "German (Germany)" },
  { id: "el-GR", name: "Greek (Greece)" },
  { id: "gu-IN", name: "Gujarati (India)" },
  { id: "he-IL", name: "Hebrew (Israel)" },
  { id: "hi-IN", name: "Hindi (India) / हिन्दी (ভারত)" },
  { id: "hu-HU", name: "Hungarian (Hungary)" },
  { id: "is-IS", name: "Icelandic (Iceland)" },
  { id: "id-ID", name: "Indonesian (Indonesia)" },
  { id: "it-IT", name: "Italian (Italy)" },
  { id: "it-CH", name: "Italian (Switzerland)" },
  { id: "ja-JP", name: "Japanese (Japan)" },
  { id: "jv-ID", name: "Javanese (Indonesia)" },
  { id: "kn-IN", name: "Kannada (India)" },
  { id: "km-KH", name: "Khmer (Cambodia)" },
  { id: "ko-KR", name: "Korean (South Korea)" },
  { id: "lo-LA", name: "Lao (Laos)" },
  { id: "lv-LV", name: "Latvian (Latvia)" },
  { id: "lt-LT", name: "Lithuanian (Lithuania)" },
  { id: "ms-MY", name: "Malay (Malaysia)" },
  { id: "ml-IN", name: "Malayalam (India)" },
  { id: "mr-IN", name: "Marathi (India)" },
  { id: "ne-NP", name: "Nepali (Nepal)" },
  { id: "no-NO", name: "Norwegian (Norway)" },
  { id: "fa-IR", name: "Persian (Iran)" },
  { id: "pl-PL", name: "Polish (Poland)" },
  { id: "pt-BR", name: "Portuguese (Brazil)" },
  { id: "pt-PT", name: "Portuguese (Portugal)" },
  { id: "ro-RO", name: "Romanian (Romania)" },
  { id: "ru-RU", name: "Russian (Russia)" },
  { id: "sr-RS", name: "Serbian (Serbia)" },
  { id: "si-LK", name: "Sinhala (Sri Lanka)" },
  { id: "sk-SK", name: "Slovak (Slovakia)" },
  { id: "sl-SI", name: "Slovenian (Slovenia)" },
  { id: "es-AR", name: "Spanish (Argentina)" },
  { id: "es-BO", name: "Spanish (Bolivia)" },
  { id: "es-CL", name: "Spanish (Chile)" },
  { id: "es-CO", name: "Spanish (Colombia)" },
  { id: "es-CR", name: "Spanish (Costa Rica)" },
  { id: "es-EC", name: "Spanish (Ecuador)" },
  { id: "es-SV", name: "Spanish (El Salvador)" },
  { id: "es-ES", name: "Spanish (Spain)" },
  { id: "es-US", name: "Spanish (United States)" },
  { id: "es-GT", name: "Spanish (Guatemala)" },
  { id: "es-HN", name: "Spanish (Honduras)" },
  { id: "es-MX", name: "Spanish (Mexico)" },
  { id: "es-NI", name: "Spanish (Nicaragua)" },
  { id: "es-PA", name: "Spanish (Panama)" },
  { id: "es-PY", name: "Spanish (Paraguay)" },
  { id: "es-PE", name: "Spanish (Peru)" },
  { id: "es-PR", name: "Spanish (Puerto Rico)" },
  { id: "es-UY", name: "Spanish (Uruguay)" },
  { id: "es-VE", name: "Spanish (Venezuela)" },
  { id: "su-ID", name: "Sundanese (Indonesia)" },
  { id: "sw-KE", name: "Swahili (Kenya)" },
  { id: "sw-TZ", name: "Swahili (Tanzania)" },
  { id: "sv-SE", name: "Swedish (Sweden)" },
  { id: "ta-IN", name: "Tamil (India)" },
  { id: "ta-SG", name: "Tamil (Singapore)" },
  { id: "ta-LK", name: "Tamil (Sri Lanka)" },
  { id: "ta-MY", name: "Tamil (Malaysia)" },
  { id: "te-IN", name: "Telugu (India)" },
  { id: "th-TH", name: "Thai (Thailand)" },
  { id: "tr-TR", name: "Turkish (Turkey)" },
  { id: "ur-PK", name: "Urdu (Pakistan)" },
  { id: "ur-IN", name: "Urdu (India)" },
  { id: "vi-VN", name: "Vietnamese (Vietnam)" },
  { id: "zu-ZA", name: "Zulu (South Africa)" }
];

// Export for ES modules compatibility or node scripting if needed
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { SUPPORTED_LANGUAGES };
}
